let errorScreen = document.querySelector(".body__error-screen");
let display = document.querySelector("#display");
let previewScreen = document.querySelector(".body__preview");

let buttonParent = document.querySelector(".body__buttons");

const calculator = {
    displayTokens: [], // Array of tokens which are derived from the attributes specified in button in HTML.
    expression: "", // Expression generated by joining tokens stored in array.
    evalTokens: [], // Array of tokens for actual expression to be evaluated
    evalExpression: "", // Expression generated by joining tokens stored in array.
    answer: 0, // Variable to store final answer
    parenthesis: 0, //Used to track if the expression uses equal number of opening and closing parenthesis.
    ceiling: 0,
    updateTokens(displayToken, evalToken) {  // Updates token array everytime a button is pressed.
        let parenthesisIndex = Number(evalToken.includes("(")) ? 1 : (evalToken === ')') ? -1 : 0;

        this.displayTokens.push(displayToken);
        this.evalTokens.push(evalToken);

        this.parenthesis += parenthesisIndex;

        this.expression = this.displayTokens.join("");
        this.evalExpression = this.evalTokens.join("");

        display.value = this.expression;
    },
    handleAction(expression) {  // Handles action events.
        if (expression === "equals") this.calculateAnswer(true);
        else if (expression === "clearDisplay") {
            this.displayTokens.length = 0;
            this.evalTokens.length = 0;

            errorScreen.innerHTML = "";

            display.value = 0;
        } else if (expression === "clear") {
            this.displayTokens.pop();
            let token = this.evalTokens.pop();

            this.expression = this.displayTokens.join("");
            this.evalExpression = this.evalTokens.join("");

            if (token === "(") this.parenthesis -= 1;
            else if (token === ")") this.parenthesis += 1;
        }
    },
    calculateAnswer(isFinalAnswer = false) { // Used to calculate answer
        if (this.parenthesis !== 0) {
            this.showError("Malformed expression.")
        }
        try {
            this.answer = 0;
            this.answer = eval(this.evalExpression);
            
            display.value = this.answer;
        } catch (err) {
            errorScreen.innerHTML = "Error while calculating expression.";
        }
    },
    showError(message) { // Shows error message on error display
        errorScreen.innerHTML = message;
    },
    clearError() { // Clear error message
        errorScreen.innerHTML = "";
    },
}

// Listen for click events on buttons.

buttonParent.addEventListener("click", (e) => {
    let displayData = e.target.getAttribute("dataDisplay");
    let expressionData = e.target.getAttribute("dataExpression");

    console.log(displayData, expressionData);
    if (e.target.getAttribute("dataType") === "action") {
        calculator.handleAction(expressionData);
    } else {
        calculator.updateTokens(displayData, expressionData);
    }
})