import calculateAnswer from "../utils/calculateAnswer.js";
import { updateDisplay, updatePreview } from "../utils/displayHandlers.js";
import { clearError, showError } from "../utils/errorHandlers.js";


const calculator = {
    displayTokens: [], // Array of tokens which are derived from the attributes specified in button in HTML.
    expression: "", // Expression generated by joining tokens stored in array.
    evalTokens: [], // Array of tokens for actual expression to be evaluated
    evalExpression: "", // Expression generated by joining tokens stored in array.
    answer: 0, // Variable to store final answer
    parenthesis: 0, //Used to track if the expression uses equal number of opening and closing parenthesis.
    ceiling: 0,
    updateTokens(displayToken, evalToken) {  // Updates token array everytime a button is pressed.
        let parenthesisIndex = Number(evalToken.includes("(")) ? 1 : ((evalToken === ')') ? -1 : 0);

        this.displayTokens.push(displayToken);
        this.evalTokens.push(evalToken);

        this.parenthesis += parenthesisIndex;

        this.updateExpressions();

        if(parenthesisIndex === 0) this.getAnswer(false);

        return;
    },
    handleAction(expression) {  // Handles action events.
        if (expression === "equals") {
            this.getAnswer(true);
        }
        else if (expression === "clearDisplay") {
            this.displayTokens.length = 0;
            this.evalTokens.length = 0;

            this.updateExpressions();
            clearError();
        } 
        else if (expression === "clear") {
            this.displayTokens.pop();
            let token = this.evalTokens.pop();

            console.log(token);

            if (token === "(") this.parenthesis -= 1;
            else if (token === ")") this.parenthesis += 1;

            this.updateExpressions();
            this.getAnswer(false);
        }

        return;
    },
    getAnswer(isFinalAnswer = false) { // Used to calculate answer
        if(this.evalExpression === "") return;

        let response = calculateAnswer(this.parenthesis, this.evalExpression);
        
        if(response?.status === 200) {
            if(isFinalAnswer){
                updateDisplay(response?.answer);
                updatePreview("");
            } else {
                updatePreview(response?.answer);
            }
        } else if(isFinalAnswer) {
            updatePreview("");
            showError(response);
        }

        return;
    },
    updateExpressions(){
        this.expression = this.displayTokens.join("");
        this.evalExpression = this.evalTokens.join("");

        if(this.expression === ""){
            updateDisplay("0");
            updatePreview("");
        } else {
            updateDisplay(this.expression);
        }
        return;
    }
}

export default calculator;